### ISSUE TITLE
no main manifest attribute, in arcturus.jar

### ISSUE THREAD

**Issue by kasperbjerby** [izinezion/ArcturusEmulator#4]
You are missing "Main-Class: com.eu.habbo.Emulator" in your META-INF/MANIFEST.MF
I got a "no main manifest attribute, in arcturus.jar" error without that..

Also the SWF download says PRODUCTION-201709192204-203982672 but the swf.rar it downloads is PRODUCTION-201601012205-226667486.. Or atleast the folder in gordon says so..

**Comment by sant0ro** [comment]
The gordon folder has a wrong name. If you mind changing it for us, that would be great.

Oh, I build the artifacts without the manifest. I'll correct this now.

Thanks. But you can also build yourself it 😄

**Comment by kasperbjerby** [comment]
When i downloaded the latest release it had a manifest file in it and all i did was add "Main-Class: com.eu.habbo.Emulator" in the file and everything worked :)

And the gordon folder name is not really important :D It was just a little confusing and i was wondering if it was the correct swf i did download..

**Comment by sant0ro** [comment]
If you want give us this edited `arcturus.jar` that would save me some time.

I'm closing this issue, since all right 😃

**Comment by kasperbjerby** [comment]
Sure :) http://daap.dk/arcturus.jar
